package studio.rollinrock.maven.archetypes.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import studio.rollinrock.maven.archetypes.entity.UserProfile;
import studio.rollinrock.maven.archetypes.entity.UserProfileExample;

@Mapper
public interface UserProfileMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_profile
     *
     * @mbg.generated Tue Jan 15 16:09:06 CST 2019
     */
    long countByExample(UserProfileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_profile
     *
     * @mbg.generated Tue Jan 15 16:09:06 CST 2019
     */
    int deleteByExample(UserProfileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_profile
     *
     * @mbg.generated Tue Jan 15 16:09:06 CST 2019
     */
    int insert(UserProfile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_profile
     *
     * @mbg.generated Tue Jan 15 16:09:06 CST 2019
     */
    int insertSelective(UserProfile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_profile
     *
     * @mbg.generated Tue Jan 15 16:09:06 CST 2019
     */
    List<UserProfile> selectByExample(UserProfileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_profile
     *
     * @mbg.generated Tue Jan 15 16:09:06 CST 2019
     */
    int updateByExampleSelective(@Param("record") UserProfile record, @Param("example") UserProfileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_profile
     *
     * @mbg.generated Tue Jan 15 16:09:06 CST 2019
     */
    int updateByExample(@Param("record") UserProfile record, @Param("example") UserProfileExample example);
}