package studio.rollinrock.maven.archetypes.entity;

public class UserProfile {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_profile.uid
     *
     * @mbg.generated Tue Jan 15 16:09:06 CST 2019
     */
    private Integer uid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_profile.name
     *
     * @mbg.generated Tue Jan 15 16:09:06 CST 2019
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_profile.biological_sex
     *
     * @mbg.generated Tue Jan 15 16:09:06 CST 2019
     */
    private String biologicalSex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_profile.local_limit
     *
     * @mbg.generated Tue Jan 15 16:09:06 CST 2019
     */
    private Integer localLimit;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_profile.uid
     *
     * @return the value of user_profile.uid
     *
     * @mbg.generated Tue Jan 15 16:09:06 CST 2019
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_profile.uid
     *
     * @param uid the value for user_profile.uid
     *
     * @mbg.generated Tue Jan 15 16:09:06 CST 2019
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_profile.name
     *
     * @return the value of user_profile.name
     *
     * @mbg.generated Tue Jan 15 16:09:06 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_profile.name
     *
     * @param name the value for user_profile.name
     *
     * @mbg.generated Tue Jan 15 16:09:06 CST 2019
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_profile.biological_sex
     *
     * @return the value of user_profile.biological_sex
     *
     * @mbg.generated Tue Jan 15 16:09:06 CST 2019
     */
    public String getBiologicalSex() {
        return biologicalSex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_profile.biological_sex
     *
     * @param biologicalSex the value for user_profile.biological_sex
     *
     * @mbg.generated Tue Jan 15 16:09:06 CST 2019
     */
    public void setBiologicalSex(String biologicalSex) {
        this.biologicalSex = biologicalSex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_profile.local_limit
     *
     * @return the value of user_profile.local_limit
     *
     * @mbg.generated Tue Jan 15 16:09:06 CST 2019
     */
    public Integer getLocalLimit() {
        return localLimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_profile.local_limit
     *
     * @param localLimit the value for user_profile.local_limit
     *
     * @mbg.generated Tue Jan 15 16:09:06 CST 2019
     */
    public void setLocalLimit(Integer localLimit) {
        this.localLimit = localLimit;
    }
}